tannerySuite/anagrafiche/urls.py
from django.urls import path

from .charts import get_country_count, get_country_count_client
from .views import *

app_name="anagrafiche"



urlpatterns = [

    # Facility
    path("aggiungi_facility_details/", FacilityCreateView.as_view(), name="aggiungi_facility_details"),    
    path("edit_facility_details/<int:pk>", FacilityUpdateView.as_view(), name="edit_facility_details"),
    path("<int:pk>/add_facility_contact", add_facility_contact, name="add_facility_contact"),
    path("<int:pk>/modifica_facility_contact/<int:id>", FacilityContactUpdateView.as_view(), name="modifica_facility_contact"),
    path("delete_facility_contact/<int:pk>", delete_facility_contact, name="delete_facility_contact"),
    #path("<int:fk_facility>/home_autorizzazioni/", home_autorizzazioni, name="home_autorizzazioni"),
    #path("<int:fk_facility>/add_facility_authorization/", FacilityAuthorizationCreateView.as_view(), name="add_facility_authorization"),
    #path("<int:fk_facility>/modifica_facility_authorization/<int:id>", FacilityAuthorizationUpdateView.as_view(), name="modifica_facility_authorization"),
    #path("delete_facility_authorization/<int:pk>", delete_facility_authorization, name="delete_facility_authorization"),

    # Clienti
    path("home_clienti/", ListaClienteView.as_view(), name="home_clienti"),
    path("aggiungi_cliente/", ClienteCreateView.as_view(), name="aggiungi_cliente"),
    path("modifica_cliente/<int:pk>", ClienteUpdateView.as_view(), name="modifica_cliente"),
    
    # Fornitori
    path("home_fornitori/", home_fornitori, name="home_fornitori"),    
    path("aggiungi_fornitore/", CreateSupplier.as_view(), name="aggiungi_fornitore"),
    path('aggiungi_fornitore_with_category/<str:category>/', aggiungi_fornitore_with_category, name='aggiungi_fornitore_with_category'),    
    path("vedi_fornitore/<int:pk>", UpdateSupplier.as_view(), name="vedi_fornitore"),
    
    path("fornitore/<int:fk_fornitore>/aggiungi_lwg/", AddLwgCertificate.as_view(), name="aggiungi_lwg"),
    path("modifica_lwg/<int:pk>", UpdateLwgCertificate.as_view(), name="modifica_lwg"),    
    path("delete_lwg/<int:pk>", delete_certificato, name="delete_lwg"),
    
    path("fornitore/<int:fk_fornitore>/aggiungi_destinazione_diversa_fornitore/", DestinazioneDiversaFornitoreCreateView.as_view(), name="aggiungi_destinazione_diversa_fornitore"),
    path("modifica_destinazione_diversa_fornitore/<int:pk>", DestinazioneDiversaFornitoreUpdateView.as_view(), name="modifica_destinazione_diversa_fornitore"),    
    path("delete_destinazione_diversa_fornitore/<int:pk>", delete_destinazione_diversa_fornitore, name="delete_destinazione_diversa_fornitore"),
    
    path("modifica_lwg/<int:fk_certificato>/add_transf_value/", XrTransferValueCreateView.as_view(), name="add_transf_value"),
    path("edit_transf_value/<int:pk>", XrTransferValueUpdateView.as_view(), name="edit_transf_value"),
    path("delete_transf_value/<int:pk>", delete_xrtransfervalue, name="delete_transf_value"),

    # Listino terzisti
    path("fornitore/<int:fk_fornitore>/aggiungi_voce_listino/", ListinoTerzistaCreateView.as_view(), name="aggiungi_voce_listino"),
    path("modifica_voce_listino/<int:pk>", ListinoTerzistaUpdateView.as_view(), name="modifica_voce_listino"),    
    path("delete_voce_listino/<int:pk>", delete_voce_listino, name="delete_voce_listino"),
    
    path("<int:fk_listino_terzista>/aggiungi_prezzo_listino/", PrezzoListinoCreateView.as_view(), name="aggiungi_prezzo_listino"),
    path("modifica_prezzo_listino/<int:pk>", PrezzoListinoUpdateView.as_view(), name="modifica_prezzo_listino"),    
    path("delete_prezzo_listino/<int:pk>", delete_prezzo_listino, name="delete_prezzo_listino"),

    # Gestori Rifiuti
    path("fornitore/<int:fk_fornitore>/aggiungi_gestore_rifiuti/", XrDocumentiGestoreCreateView.as_view(), name="aggiungi_gestore_rifiuti"),
    path("modifica_gestore_rifiuti/<int:pk>", XrDocumentiGestoreUpdateView.as_view(), name="modifica_gestore_rifiuti"),    
    path("delete_gestore_rifiuti/<int:pk>", delete_gestore_rifiuti, name="delete_gestore_rifiuti"),

    # Listino Clienti
    path("cliente/<int:fk_cliente>/aggiungi_voce_listino_cliente/", ListinoClienteCreateView.as_view(), name="aggiungi_voce_listino_cliente"),
    path("modifica_voce_listino_cliente/<int:pk>", ListinoClienteUpdateView.as_view(), name="modifica_voce_listino_cliente"),    
    path("delete_voce_listino_cliente/<int:pk>", delete_voce_listino_cliente, name="delete_voce_listino_cliente"),
    
    # Tabelle Generiche
    path('tabelle_generiche/', tabelle_generiche, name="tabelle_generiche"),
    
    # Generiche - Transfer Values    
    path("add_transfer_values/", TransferValueCreateView.as_view(), name="add_transfer_values"),
    path("edit_transfer_values/<int:pk>", TransferValueUpdateView.as_view(), name="edit_transfer_values"),
    path("delete_transfer_value/<int:pk>", delete_transfer_value, name="delete_transfer_value"),

    # Charts
    path('get_country_count/', get_country_count, name='get_country_count'),
    path('get_country_count_client/', get_country_count_client, name='get_country_count_client'),
    

    
]

tannerySuite/core/urls.py
from django.urls import path


from .views import *
from .searches import *
from .utils import carica_destinazioni

app_name="core"



urlpatterns = [

    # Facility
    

    # Clienti
    
    
    # Fornitori
    #path("home_fornitori/", home_fornitori, name="home_fornitori"),    
    # Ricerche
    path('search_articolo/', search_articolo, name='search_articolo'),
    path('search_colore/', search_colore, name='search_colore'),
    path('search_supplier/', search_supplier, name='search_supplier'),
    path('search_outsourcing/', search_outsourcing, name='search_outsourcing'),
    path('search_fase_lavoro/', search_fase_lavoro, name="search_fase_lavoro"), # Fase lavoro
    
    path('carica_destinazioni/', carica_destinazioni, name='carica_destinazioni'),

    
]

tannerySuite/anagrafiche/views.py
import datetime

from articoli.models import ListinoCliente, ListinoTerzista, PrezzoListino
from django.apps import apps
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.utils import IntegrityError
from django.forms.models import modelform_factory
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django_filters.views import FilterView
from nonconformity.models import RapportoNC

from .filters import ClienteFilter, FornitoreFilter, TransferValueFilter
from .forms import (FormCliente, FormFacility, FormFacilityContact,
                    FormFornitore, FormFornitoreLavorazioniEsterne,
                    FormFornitorePelli, FormFornitoreProdottiChimici,
                    FormFornitoreServizi, FormLwgFornitore, FormTransferValue,
                    FormXrDocumentiGestore, FormXrTransferValueLwgFornitore,
                    ListinoClienteModelForm, ListinoTerzistaModelForm,
                    PrezzoListinoModelForm, DestinazioneDiversaFornitoreModelForm)
from .models import (Cliente, Facility, FacilityContact, Fornitore,
                    FornitoreLavorazioniEsterne, FornitorePelli,
                    FornitoreProdottiChimici, FornitoreRifiuti,
                    FornitoreServizi, LwgFornitore, TransferValue,
                    XrDocumentiGestore, XrDocumentiSmaltitore,
                    XrDocumentiTrasportatore, XrTransferValueLwgFornitore,
                    DestinazioneDiversaFornitore,
                    )

# Create your views here.

def home_fornitori(request): 
    fornitori = Fornitore.objects.all()
    fornitori_filter = FornitoreFilter(request.GET, queryset=fornitori)
    #filterset_class = FornitoreFilter
    page = request.GET.get('page', 1)
    paginator = Paginator(fornitori_filter.qs, 50)  # Utilizza fornitori_filter.qs per la paginazione
            
    try:
        fornitori_paginator = paginator.page(page)
    except PageNotAnInteger:
        fornitori_paginator = paginator.page(1)
    except EmptyPage:
        fornitori_paginator = paginator.page(paginator.num_pages)
        
    context = {
        #'fornitori': filterset_class,
        'fornitori_paginator': fornitori_paginator,
        'filter': fornitori_filter,
        'CHOICES_CATEGORY': Fornitore.CHOICES_CATEGORY
    }
    return render(request, 'anagrafiche/home_fornitori.html', context)


class UpdateSupplier(LoginRequiredMixin, UpdateView):
    model = Fornitore
    template_name = 'anagrafiche/fornitore.html'
    form_class = FormFornitore
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = self.get_form()  # Utilizza il form principale per Fornitore 
        context["pk_fornitore"] = self.object.pk
        # Ottieni l'istanza di Categoria correlata al Fornitore attuale
        categoria_model_name = f'Fornitore{self.object.categoria.title().replace(" ", "")}'
        
        if categoria_model_name != 'FornitoreNessuna':
            categoria_model = apps.get_model(app_label='anagrafiche', model_name=categoria_model_name)
            
            
            if categoria_model:
                print("categoria_model:" + str(categoria_model))
                categoria_instance = categoria_model.objects.filter(fornitore_ptr=self.object).first() 
                if categoria_instance:
                    CategoriaForm = modelform_factory(categoria_model, exclude=['fornitore'])
                    nome_form_secondario = CategoriaForm.__name__            
                    context["nome_form_secondario"] = nome_form_secondario            
                    modello_form = CategoriaForm(instance=categoria_instance)            
                    context["modello_form"] = modello_form
                else:
                    context["categoria_instance_missing"] = True  # Aggiungi questa chiave al contesto
                    
        context["lwg_certs"] = LwgFornitore.objects.filter(fk_fornitore_id=self.object.pk) 
        context["nc_associate"] = RapportoNC.objects.filter(fk_fornitore=self.object.pk)
        context["listini_terzisti"] = ListinoTerzista.objects.filter(fk_fornitore=self.object.pk)
        context["gestori_rifiuti"] = XrDocumentiGestore.objects.filter(fornitore_rifiuti=self.object.pk)
        context["smaltitori_rifiuti"] = XrDocumentiSmaltitore.objects.filter(fornitore_rifiuti=self.object.pk)
        context["trasportatori_rifiuti"] = XrDocumentiTrasportatore.objects.filter(fornitore_rifiuti=self.object.pk)
        context["destinazioni_diverse"] = DestinazioneDiversaFornitore.objects.filter(fk_fornitore=self.object.pk)
        print(f"fk_fornitore: {self.object.pk}")
        return context
    
    

    def get_success_url(self):        
        if 'salva_esci' in self.request.POST:
            return reverse_lazy('anagrafiche:home_fornitori')
        
        pk_fornitore=self.object.pk
        return reverse_lazy('anagrafiche:vedi_fornitore', kwargs={'pk':pk_fornitore})

    
    def form_valid(self, form):        
        messages.info(self.request, 'Il fornitore è stato modificato!') # Compare sul success_url
        return super().form_valid(form)
    
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()

        if form.is_valid():
            categoria_model_name = f'Fornitore{self.object.categoria.title().replace(" ", "")}'
            if categoria_model_name != 'FornitoreNessuna':
                categoria_model = apps.get_model(app_label='anagrafiche', model_name=categoria_model_name)
                if categoria_model:
                    categoria_instance = categoria_model.objects.filter(fornitore_ptr=self.object).first()

                    if not categoria_instance:
                        categoria_instance = categoria_model.objects.create(fornitore_ptr=self.object)

                    CategoriaForm = modelform_factory(categoria_model, exclude=['fornitore'])
                    categoria_form = CategoriaForm(request.POST, instance=categoria_instance)
                    if categoria_form.is_valid():
                        categoria_form.save()

            return self.form_valid(form)
        else:
            return self.form_invalid(form)

        
    def form_invalid(self, form):
        #messages.error(self.request, 'Errore! Il fornitore non è stato aggiunto!')
        return super().form_invalid(form)



def aggiungi_fornitore_with_category(request, category):
    context = {
        'category': category,
        'CHOICES_CATEGORY': Fornitore.CHOICES_CATEGORY,
    }
    return render(request, 'anagrafiche/aggiungi_fornitore_modal.html', context)



class CreateSupplier(LoginRequiredMixin, CreateView):
    
    model = Fornitore
    form_class = FormFornitore
    success_message = 'Fornitore aggiunto correttamente!'
    error_message = 'Error saving the Doc, check fields below.'
    template_name = "anagrafiche/fornitore.html"
    
    

    def get_initial(self):
        initial = super().get_initial()
        created_by = self.request.user
        categoria = self.request.GET.get('categoria')
        if categoria in dict(Fornitore.CHOICES_CATEGORY):
            initial['categoria'] = categoria
            print("categoria initial: " + str(categoria))
        initial['created_by']= created_by
        initial['created_at']= datetime.datetime.now()
        return initial
        
    def get_success_url(self):        
        if 'salva_esci' in self.request.POST:
            return reverse_lazy('anagrafiche:home_fornitori')
        
        pk_fornitore=self.object.pk
        print("pk_fornitore: " + str(pk_fornitore))
        return reverse_lazy('anagrafiche:vedi_fornitore', kwargs={'pk':pk_fornitore})
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['CHOICES_CATEGORY'] = Fornitore.CHOICES_CATEGORY
        return context
    
    
    def form_valid(self, form):
        forn = form.save(commit=False)
        forn.created_by = self.request.user
        forn.created_at = datetime.datetime.now()
        categoria = form.cleaned_data["categoria"]
        forn.save()

        print("categoria: " + str(categoria))

        if categoria == Fornitore.NESSUNA:  # Nessuna categoria selezionata
            forn.save()
            messages.info(self.request, 'Il fornitore è stato aggiunto!')
            self.object = forn
            return HttpResponseRedirect(self.get_success_url())

        categoria_model_name = f'Fornitore{categoria.title().replace(" ", "")}'
        print("categoria_model_name: " + str(categoria_model_name))
        categoria_model = apps.get_model(app_label='anagrafiche', model_name=categoria_model_name)

        if categoria_model:
            try:
                # Crea l'istanza del modello specifico per la categoria senza salvarla
                categoria_instance = categoria_model(fornitore_ptr=forn)

                # Aggiungi qui la mappatura tra categoria e attributo forn.fornitore_ptr_* corretto
                categoria_attr_map = {
                    'FornitorePelli': 'fornitore_ptr_pelli',
                    'FornitoreProdottiChimici': 'fornitore_ptr_prodottichimici',
                    'FornitoreManutenzioni': 'fornitore_ptr_manutenzioni',
                    'FornitoreLavorazioniEsterne': 'fornitore_ptr_lavorazioniesterne',
                    'FornitoreServizi': 'fornitore_ptr_servizi',
                    'FornitoreRifiuti': 'fornitore_ptr_rifiuti',
                    # Aggiungi altri se necessario
                }

                categoria_attr = categoria_attr_map.get(categoria_model_name)

tannerySuite/anagrafiche/templates/anagrafiche/facility.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% block title %}{{ block.super }} | Anagrafiche - Facility {% endblock %}

{% block sidenav %}
{% include "core/partials/_sidenav_anagrafiche.html" %}
{% endblock %}

{% block content %}
{% include 'core/modals/delConfirm.html' %}


<nav aria-label="breadcrumb" class="mt-3">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>              
        <li class="breadcrumb-item active" aria-current="page">Facility Details</li>
    </ol>
</nav>

    <div class="container">
        
        <h3>Facility Details</h3>
        <hr>
        {% include "core/partials/_messages.html" %}
        
        <br>

        
        <form method="post" enctype="multipart/form-data">

            {% csrf_token %}
            <div class="row">
                <div class="col-sm-4">
                    
                    {{ form.nome_sito|as_crispy_field}}
                </div>
                <div class="col-sm-4">
                    {{ form.urn|as_crispy_field}}
                </div>
                <div class="col-sm-4">
                    {{ form.logo|as_crispy_field}}
                </div>
            </div>

            <div class="row">
                <div class="col-6">
                    {{ form.piva|as_crispy_field}}
                </div>
                <div class="col-3">
                    {{ form.phone|as_crispy_field}}
                </div>
            </div>

            <div class="row">
                <div class="col-4">
                    {{ form.indirizzo|as_crispy_field}}
                </div>
                <div class="col-1">
                    {{ form.cap|as_crispy_field}}
                </div>
                <div class="col-3">
                    {{ form.city|as_crispy_field}}
                </div>
                <div class="col-1">
                    {{ form.provincia|as_crispy_field}}
                </div>
                <div class="col-3">
                    {{ form.country|as_crispy_field}}
                </div>
            </div>
            <div class="row">
                <div class="col-3">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">Categorie</h6>
                            
                            <div class="col">
                                {{ form.primary_cat|as_crispy_field}}
                            </div>
                            <div class="col">
                                {{ form.secondary_cat|as_crispy_field}}
                            </div>
                            <div class="col">
                                {{ form.tertiary_cat|as_crispy_field}}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-3">
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title">Geo-dati</h6>
                            
                            <div class="col">
                                {{ form.site_area|as_crispy_field}}
                            </div>
                            <div class="col">
                                {{ form.latitude|as_crispy_field}}
                            </div>
                            <div class="col">
                                {{ form.longitude|as_crispy_field}}
                            </div>
                            <button type="button" class="btn btn-sm btn-success" onclick="openGoogleMaps()"><i class="bi bi-geo-alt"></i> Apri su Google Maps</button>
                        </div>
                    </div>
                </div>

                <div class="col-6">
                    <div class="card">
                        <div class="card-body">
                          <h6 class="card-title">Contatti</h6>
                          <div class="table-container">
                            <div class="table-responsive-sm">
                                <table class="table table-fixed-header table-hover table-striped table-bordered">
                                <thead class="thead-dark mt-0">
                                    <tr>   
                                        <th>Nome e Cognome</th>
                                        <th>Tipo contatto</th>                                    
                                        <th>Posizione</th>
                                        <th>Azione</th>
                                    
                                    </tr>
                                </thead>
                                
                                <tbody>
                                
                                    {% for facility_contact in facility_contacts %}
                                    <tr>
                                    <td ><a href="{% url 'anagrafiche:modifica_facility_contact' pk=facility.pk id=facility_contact.pk %}">{{ facility_contact.name }}</a>                
                                        <p></p>
                                    </td>
                                    <td class="max-width-cell" style="word-wrap: break-all;">       
                                        <p>{{ facility_contact.contact_type }}</p>
                                    </td>
                                    <td >                
                                        <p>{{ facility_contact.position }}</p>
                                    </td>
                                    <td class="text-center"><a href="{% url 'anagrafiche:delete_facility_contact' pk=facility_contact.pk %}" class="btn btn-sm btn-outline-danger confirm-delete" title="Delete" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" id="deleteButton{{facility_contact.pk}}"><i class="bi bi-trash"></i>Elimina</a></td>             
                                    </tr>
                                    {% endfor %}
                                    
                                
                            
                                
                                
                                </tbody>
                                
                                </table>
                            </div>

                          </div>
                          <tfoot>
                            <a href="{% url 'anagrafiche:add_facility_contact' facility.pk %}" class="btn btn-sm btn-success mt-2">Aggiungi Contatto</a>
                        </tfoot>
                          
                          
                        </div>
                      </div>
                </div>
            </div>
            <div class="row">
                {{ form.facility_description|as_crispy_field}}
            </div>

            
            <input type="submit" class="btn btn-success mb-2 me-1" value="Salva">
            <button type="button" class="btn btn-danger mb-2 me-1" onclick="goBack()"><i class="bi bi-arrow-counterclockwise"></i> Annulla</button>
        </form>
    </div>



{% endblock %}

{% block extra_scripts %}
<script>
    function openGoogleMaps() {
        var latitudine = document.getElementById("id_latitude").value;
        var longitudine = document.getElementById("id_longitude").value;

        if (latitudine && longitudine) {
            var url = "https://www.google.com/maps/search/?api=1&query=" + latitudine + "," + longitudine;
            window.open(url);
        } else {
            alert("Completa i campi Latitudine e Longitudine prima di aprire Google Maps.");
        }
    }

document.addEventListener("DOMContentLoaded", function() {
            setFocusOnField('id_nome_sito');
        });
</script>
{% endblock %}

tannerySuite/anagrafiche/templates/anagrafiche/home_clienti.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% block title %}{{ block.super }} | Anagrafiche - Fornitori {% endblock %}

{% block sidenav %}
{% include "core/partials/_sidenav_anagrafiche.html" %}
{% endblock %}

{% block content %}


<nav aria-label="breadcrumb" class="mt-3">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>      
        <li class="breadcrumb-item active" aria-current="page">Clienti</li>
    </ol>
</nav>

    <div class="container">
        
        <h3>Anagrafiche Clienti</h3>
        <br>
        {% include "core/partials/_messages.html" %}

        <!-- Riga grafici e statistiche -->
        <div class="row">
          <div class="col-4">        
            <canvas id="country_count" data-url=""></canvas>
          </div>
        </div>
        <!-- Fine riga grafici e statistiche -->
        

        <!-- Valutare se tenere il filtro in javascript DataTable -->
        <!-- Inizio filtro -->
        <!-- <div class="row">
          <div class="col">
            <div class="card card-body">
        
              
              <form method="get">
        
                <div class="table-responsive-sm">
                  <table class="table table-hover table-striped table-bordered">
                    <thead class="thead-dark">
                      <tr>     
                        <th>Ragione Sociale</th>
                        
                        
                      </tr>
                    </thead>
                    
                    <tbody>
                    <tr>
                      <td style="width: 20%">                
                        {% render_field filter.form.ragionesociale class="form-control" %}
                      </td>
                      
                      
                      
                    </tr>
              
                    
                    
                  </tbody>
                  </table>
                </div>
                  
        
                
        
                <button class="btn btn-primary" type="submit"><i class="bi bi-search"></i>&nbsp;&nbsp; Cerca</button>
                <a class="btn btn-success" href="{% url 'anagrafiche:home_clienti' %}"><i class="bi bi-arrow-counterclockwise"></i>&nbsp;&nbsp; Pulisci campi</a>
                
              </form>
              
              
            </div>
          </div>
          
        </div> -->
        <!-- Fine filtro -->

        <hr>
        <div class="d-flex flex-row-reverse bd-highlight">
        <a href="{% url 'anagrafiche:aggiungi_cliente' %}" class="btn btn-success p-2 bd-highlight"><i class="bi bi-person-plus"></i> Aggiungi Cliente</a>
        </div>  
        <br>


        <div class="container-fluid">
            <div class="table-responsive">
            <table class="table table-hover table-striped table-bordered" id="TabellaClienti">
              <thead class="thead-dark">
              <tr>        
                <th>Ragione Sociale</th>
                <th>Indirizzo</th>
                <th>Paese</th>
                
                
                
                            
              </tr>
            </thead>
              
              <tbody>
                {% for cliente in initial_clienti %}
                    
                    <td class="col-md-1"><a href="{{ cliente.get_absolute_url }}">{{ cliente.ragionesociale }}</a></td>
                    <td class="col-md-2">{{ cliente.indirizzo }}</td>  
                    <td class="col-md-2">{{ cliente.country  }} <img class="country-select-flag" id="{ flag_id }" style="max-height: 24px;" src="{{ cliente.country.flag  }}"></td>                    
                  </tr>
                
                {% endfor %}
                
              </tbody>
            </table>
             
          </div>
    </div>
    </div>



{% endblock %}

{% block extra_scripts %}
<script>
  

  document.addEventListener('DOMContentLoaded', function() {
        var ctx = document.getElementById('country_count').getContext('2d');
        
        fetch('{% url 'anagrafiche:get_country_count_client' %}')
            .then(response => response.json())
            .then(data => {
                var myChart = new Chart(ctx, {
                    type: 'bar',
                    data: {
                        labels: data.labels,
                        datasets: [{
                            label: 'Conteggio Clienti per Nazione',
                            data: data.data,
                            backgroundColor: 'rgba(54, 162, 235, 0.5)',
                            borderColor: 'rgba(54, 162, 235, 1)',
                            borderWidth: 1
                        }]
                    },
                    options: {
                        scales: {
                            y: {
                                beginAtZero: true,
                                precision: 0
                            }
                        }
                    }
                });
            });
    });



        document.addEventListener("DOMContentLoaded", function() {
            initializeDataTable('TabellaClienti');
        });
    


</script>
{% endblock %}

tannerySuite/anagrafiche/templates/anagrafiche/lwg_transfer_values.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% block title %}{{ block.super }} | Anagrafiche - Fornitori {% endblock %}

{% block sidenav %}
{% include "core/partials/_sidenav_anagrafiche.html" %}
{% endblock %}

{% block content %}


<nav aria-label="breadcrumb" class="mt-3">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>      
        <li class="breadcrumb-item"><a href="{% url 'anagrafiche:home_fornitori' %}">Fornitori</a></li>        
        <li class="breadcrumb-item"><a href="{% url 'anagrafiche:vedi_fornitore' pk=fornitore.pk %}">{{ fornitore.ragionesociale }}</a></li>
        <li class="breadcrumb-item"><a href="{% url 'anagrafiche:modifica_lwg' pk=certificato.pk %}">{{ certificato.lwg_urn }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">Transfer Values</li>
        
    </ol>
</nav>

    <div class="container">
        {% if form.instance.id  %}
            <h3>Modifica Transfer Value</h3>
        {% else %}
            <h3> Aggiungi Transfer Value</h3>
        {% endif %}
        
        
        <hr>
        
        
        
        
        <br>


        <form method="post">
            {% csrf_token %}

            

            <div class="row">
                
                <div class="col-3">
                    {{ form.fk_transfervalue|as_crispy_field }}
                </div>
                <div class="col-3">
                    {{ form.quantity|as_crispy_field }}
                </div>
                <div class="col-6">
                    {{ form.note|as_crispy_field }}
                </div>

                
            </div>
            <div class="row">
                <div class="col-3">
                    {{ form.fk_lwgcertificato|as_crispy_field }}
                </div>
                <div class="col-3">
                    {{ form.created_by|as_crispy_field }}
                </div>
            </div>
            
            

            
            <input type="submit" class="btn btn-success mb-2 me-1" value="Salva">
            <button type="button" class="btn btn-danger mb-2 me-1" onclick="goBack()"><i class="bi bi-arrow-counterclockwise"></i> Annulla</button>
        </form>
        <hr>
        
        
    </div>



{% endblock %}

{% block extra_scripts %}

{% endblock %} 