tannerySuite/articoli/urls.py
from django.urls import path

from .utils import *
from .views import *

app_name="articoli"



urlpatterns = [

    # Home Articoli
    path("", articoli_home, name="articoli_home"),    
    path("crea_articolo/", ArticoloCreateView.as_view(), name="crea_articolo"),    
    path("modifica_articolo/<int:pk>", ArticoloUpdateView.as_view(), name="modifica_articolo"),    
    path("delete_articolo/<int:pk>", delete_articolo, name="delete_articolo"), 
    
    # Home Colori
    path("colori/", colori_home, name="colori_home"),    
    path("colori/crea_colore/", ColoreCreateView.as_view(), name="crea_colore"),    
    path("colori/modifica_colore/<int:pk>", ColoreUpdateView.as_view(), name="modifica_colore"),    
    path("colori/delete_colore/<int:pk>", delete_colore, name="delete_colore"),    
    
    # Tabelle Generiche
    path("tabelle_generiche/", tabelle_generiche, name="tabelle_generiche"),

    # Fasi di Lavoro       
    path("crea_fase_lavoro/", FaseLavoroCreateView.as_view(), name="crea_fase_lavoro"),    
    path("modifica_fase_lavoro/<int:pk>", FaseLavoroUpdateView.as_view(), name="modifica_fase_lavoro"),    
    path("delete_fase_lavoro/<int:pk>", delete_fase_lavoro, name="delete_fase_lavoro"), 

    # Attributo fasi di lavoro
    path('<int:fk_fase_lavoro>/aggiungi_attributo/', DettaglioFaseLavoroCreateView.as_view(), name="aggiungi_attributo"), 
    path('<int:fk_fase_lavoro>/modifica_attributo/<int:pk>/', DettaglioFaseLavoroUpdateView.as_view(), name="modifica_attributo"), 
    path('delete_attributo/<int:pk>', delete_dettaglio_fase_lavoro, name="delete_attributo"),
    
    # Lavorazioni Esterne      
    path("crea_lavorazione/", LavorazioneCreateView.as_view(), name="crea_lavorazione"),    
    path("modifica_lavorazione/<int:pk>", LavorazioneUpdateView.as_view(), name="modifica_lavorazione"),    
    path("delete_lavorazione/<int:pk>", delete_lavorazione, name="delete_lavorazione"), 

    # Elenco Test      
    path("crea_test/", ElencoTestCreateView.as_view(), name="crea_test"),    
    path("modifica_test/<int:pk>", ElencoTestUpdateView.as_view(), name="modifica_test"),    
    path("delete_test/<int:pk>", delete_test, name="delete_test"), 

    # Test Articolo
    path('<int:fk_articolo>/aggiungi_test_articolo/', TestArticoloCreateView.as_view(), name="aggiungi_test_articolo"), 
    path('<int:fk_articolo>/modifica_test_articolo/<int:pk>/', TestArticoloUpdateView.as_view(), name="modifica_test_articolo"), 
    path('delete_test_articolo/<int:pk>', delete_test_articolo, name="delete_test_articolo"),
    
    # Procedura
    path('<int:fk_articolo>/aggiungi_procedura/', ProceduraCreateView.as_view(), name="aggiungi_procedura"), 
    path('<int:fk_articolo>/modifica_procedura/<int:pk>/', ProceduraUpdateView.as_view(), name="modifica_procedura"), 
    path('delete_procedura/<int:pk>', delete_procedura, name="delete_procedura"),
    
    # Dettaglio Procedura
    path('<int:fk_procedura>/aggiungi_dettaglio_procedura/', DettaglioProceduraCreateView.as_view(), name="aggiungi_dettaglio_procedura"), 
    path('<int:fk_procedura>/modifica_dettaglio_procedura/<int:pk>/', DettaglioProceduraUpdateView.as_view(), name="modifica_dettaglio_procedura"), 
    path('delete_dettaglio_procedura/<int:pk>', delete_dettaglio_procedura, name="delete_dettaglio_procedura"),

    # Caratteristica Procedura
    path('<int:fk_dettaglio_procedura>/aggiungi_caratteristica_procedura/', CaratteristicaProceduraCreateView.as_view(), name="aggiungi_caratteristica_procedura"), 
    path('<int:fk_dettaglio_procedura>/modifica_caratteristica_procedura/<int:pk>/', CaratteristicaProceduraUpdateView.as_view(), name="modifica_caratteristica_procedura"), 
    path('delete_caratteristica_procedura/<int:pk>', delete_caratteristica_procedura, name="delete_caratteristica_procedura"),

    # Automatismi
    path('accoda_dettaglio_fase_lavoro/', accoda_dettaglio_fase_lavoro, name="accoda_dettaglio_fase_lavoro"),
    path('accoda_caratteristiche_fase_lavoro_dettaglio_procedura/', accoda_caratteristiche_fase_lavoro_dettaglio_procedura, name="accoda_caratteristiche_fase_lavoro_dettaglio_procedura"),

    
]

tannerySuite/core/urls.py
from django.urls import path


from .views import *
from .searches import *
from .utils import carica_destinazioni

app_name="core"



urlpatterns = [

    # Facility
    

    # Clienti
    
    
    # Fornitori
    #path("home_fornitori/", home_fornitori, name="home_fornitori"),    
    # Ricerche
    path('search_articolo/', search_articolo, name='search_articolo'),
    path('search_colore/', search_colore, name='search_colore'),
    path('search_supplier/', search_supplier, name='search_supplier'),
    path('search_outsourcing/', search_outsourcing, name='search_outsourcing'),
    path('search_fase_lavoro/', search_fase_lavoro, name="search_fase_lavoro"), # Fase lavoro
    
    path('carica_destinazioni/', carica_destinazioni, name='carica_destinazioni'),

    
]

tannerySuite/articoli/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import F
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView

from .filters import *
from .forms import *
from .models import (Articolo, Colore, DettaglioProcedura, ElencoTest,
                    FaseLavoro, Procedura, TestArticolo)


def articoli_home(request):
    articoli = Articolo.objects.all()
    articolo_filter = ArticoloFilter
    page = request.GET.get('page', 1)
    paginator = Paginator(articoli, 50)
    
    try:
        articoli_home = paginator.page(page)
    except PageNotAnInteger:
        articoli_home = paginator.page(1)
    except EmptyPage:
        articoli_home = paginator.page(paginator.num_pages)
    context={
        'articoli_home': articoli_home,
        'filter': articolo_filter,
        
    }
    return render(request, "articoli/articoli_home.html", context)



class ArticoloCreateView(LoginRequiredMixin,CreateView):
    model = Articolo
    form_class = ArticoloModelForm
    template_name = 'articoli/articolo.html'
    success_message = 'Articolo aggiunto correttamente!'
    #success_url = reverse_lazy('human_resources:human_resources')

    def get_success_url(self):        
        if 'salva_esci' in self.request.POST:
            return reverse_lazy('articoli:articoli_home')
        
        pk_articolo=self.object.pk
        return reverse_lazy('articoli:modifica_articolo', kwargs={'pk':pk_articolo})
    
    def form_valid(self, form):        
        messages.info(self.request, self.success_message) # Compare sul success_url
        return super().form_valid(form)
    
    def get_initial(self):
        created_by = self.request.user
        
        return {
            'created_by': created_by,
        }
    
    

class ArticoloUpdateView(LoginRequiredMixin,UpdateView):
    model = Articolo
    form_class = ArticoloModelForm
    template_name = 'articoli/articolo.html'
    success_message = 'Articolo modificato correttamente!'
    #success_url = reverse_lazy('human_resources:human_resources')

    def form_valid(self, form):        
        messages.info(self.request, self.success_message) # Compare sul success_url
        return super().form_valid(form)
    
    def get_success_url(self):        
        if 'salva_esci' in self.request.POST:
            return reverse_lazy('articoli:articoli_home')
        
        pk_articolo=self.object.pk
        return reverse_lazy('articoli:modifica_articolo', kwargs={'pk':pk_articolo})
    
    def get_context_data(self, **kwargs):        
        context = super().get_context_data(**kwargs)
        context['elenco_test'] = TestArticolo.objects.filter(fk_articolo=self.object.pk)
        context['elenco_revisioni'] = Procedura.objects.filter(fk_articolo=self.object.pk).order_by('-data_procedura', '-data_revisione')
        return context
    
def delete_articolo(request, pk): 
        deleteobject = get_object_or_404(Articolo, pk = pk)        
        deleteobject.delete()
        url_match= reverse_lazy('articoli:articoli_home')
        return redirect(url_match)
    


def colori_home(request):
    colori = Colore.objects.all()
    colore_filter = ColoreFilter
    page = request.GET.get('page', 1)
    paginator = Paginator(colori, 50)
    
    try:
        colori_home = paginator.page(page)
    except PageNotAnInteger:
        colori_home = paginator.page(1)
    except EmptyPage:
        colori_home = paginator.page(paginator.num_pages)
    context={
        'colori_home': colori_home,
        'filter': colore_filter,
        
    }
    return render(request, "articoli/colori_home.html", context)


class ColoreCreateView(LoginRequiredMixin,CreateView):
    model = Colore
    form_class = ColoreModelForm
    template_name = 'articoli/colore.html'
    success_message = 'Colore aggiunto correttamente!'
    #success_url = reverse_lazy('human_resources:human_resources')

    def get_success_url(self):        
        if 'salva_esci' in self.request.POST:
            return reverse_lazy('articoli:colori_home')
        
        pk_colore=self.object.pk
        return reverse_lazy('articoli:modifica_colore', kwargs={'pk':pk_colore})
    
    def form_valid(self, form):        
        messages.info(self.request, self.success_message) # Compare sul success_url
        return super().form_valid(form)
    
    

class ColoreUpdateView(LoginRequiredMixin,UpdateView):
    model = Colore
    form_class = ColoreModelForm
    template_name = 'articoli/colore.html'
    success_message = 'Colore modificato correttamente!'
    #success_url = reverse_lazy('human_resources:human_resources')

    def form_valid(self, form):        
        messages.info(self.request, self.success_message) # Compare sul success_url
        return super().form_valid(form)
    
    def get_success_url(self):        
        if 'salva_esci' in self.request.POST:
            return reverse_lazy('articoli:colori_home')
        
        pk_colore=self.object.pk
        return reverse_lazy('articoli:modifica_colore', kwargs={'pk':pk_colore})
    
    def get_context_data(self, **kwargs):        
        context = super().get_context_data(**kwargs)
        # context['elenco_formazione'] = DettaglioRegistroFormazione.objects.filter(fk_hr=self.object.pk)
        # context['elenco_valutazioni'] = ValutazioneOperatore.objects.filter(fk_hr=self.object.pk)
        return context
    
def delete_colore(request, pk): 
        deleteobject = get_object_or_404(Colore, pk = pk)        
        deleteobject.delete()
        url_match= reverse_lazy('articoli:colori_home')
        return redirect(url_match)
    



def tabelle_generiche(request):

    # Fasi di Lavoro
    fasi_lavoro = FaseLavoro.objects.all()
    tot_fasi = FaseLavoro.objects.count()
    fasi_lavoro_filter = FaseLavoroFilter(request.GET, queryset=fasi_lavoro)
    filtered_fasi_lavoro = fasi_lavoro_filter.qs
    fase_lavoro_filter_count = filtered_fasi_lavoro.count()
    
    # Paginazione Fasi di Lavoro
    page_fasi_lavoro = request.GET.get('page', 1)
    paginator_fasi_lavoro = Paginator(filtered_fasi_lavoro, 50)
    try:
        fasi_lavoro_paginator = paginator_fasi_lavoro.page(page_fasi_lavoro)
    except PageNotAnInteger:
        fasi_lavoro_paginator = paginator_fasi_lavoro.page(1)
    except EmptyPage:
        fasi_lavoro_paginator = paginator_fasi_lavoro.page(paginator_fasi_lavoro.num_pages)


    # Elenco Test
    elenco_test = ElencoTest.objects.all()
    tot_test = ElencoTest.objects.count()
    elenco_test_filter = ElencoTestFilter(request.GET, queryset=elenco_test)
    filtered_elenco_test = elenco_test_filter.qs
    elenco_test_filter_count = filtered_elenco_test.count()
    
    # Paginazione Elenco Test
    page_elenco_test = request.GET.get('page', 1)
    paginator_elenco_test = Paginator(filtered_elenco_test, 50)
    try:
        elenco_test_paginator = paginator_elenco_test.page(page_elenco_test)
    except PageNotAnInteger:
        elenco_test_paginator = paginator_elenco_test.page(1)
    except EmptyPage:
        elenco_test_paginator = paginator_elenco_test.page(paginator_elenco_test.num_pages)

    
    # Elenco Lavorazioni
    elenco_lavorazioni = Lavorazione.objects.all()
    tot_lavorazioni_esterne = Lavorazione.objects.count()
    lavorazioni_esterne_filter = LavorazioneEsternaFilter(request.GET, queryset=elenco_lavorazioni)
    filtered_elenco_lavorazioni = lavorazioni_esterne_filter.qs
    lavorazioni_esterne_filter_count = filtered_elenco_lavorazioni.count()
    
    # Paginazione Elenco Test
    page_lavorazioni_esterne = request.GET.get('page', 1)
    paginator_lavorazioni_esterne = Paginator(filtered_elenco_lavorazioni, 50)
    try:
        lavorazioni_esterne_paginator = paginator_lavorazioni_esterne.page(page_lavorazioni_esterne)
    except PageNotAnInteger:
        lavorazioni_esterne_paginator = paginator_lavorazioni_esterne.page(1)
    except EmptyPage:
        lavorazioni_esterne_paginator = paginator_lavorazioni_esterne.page(paginator_lavorazioni_esterne.num_pages)



    context={
        
        'filter': fasi_lavoro_filter,
        'tot_fasi': tot_fasi,
        'fase_lavoro_filter_count': fase_lavoro_filter_count,
        'fasi_lavoro_paginator': fasi_lavoro_paginator,
        'elenco_test_filter': elenco_test_filter,
        'tot_test': tot_test,
        'elenco_test_filter_count': elenco_test_filter_count,
        'elenco_test_paginator': elenco_test_paginator,
        'lavorazioni_esterne_filter': lavorazioni_esterne_filter,
        'tot_lavorazioni_esterne': tot_lavorazioni_esterne,
        'lavorazioni_esterne_filter_count': lavorazioni_esterne_filter_count,
        'lavorazioni_esterne_paginator': lavorazioni_esterne_paginator,
        
    }
    return render(request, "articoli/tabelle_generiche.html", context)


class FaseLavoroCreateView(LoginRequiredMixin,CreateView):
    model = FaseLavoro
    form_class = FaseLavoroModelForm
    template_name = 'articoli/fase_lavoro.html'
    success_message = 'Fase di lavoro aggiunta correttamente!'
    #success_url = reverse_lazy('human_resources:human_resources')

    def get_success_url(self):        
        if 'salva_esci' in self.request.POST:
            return reverse_lazy('articoli:tabelle_generiche')
        
        pk_fase=self.object.pk
        return reverse_lazy('articoli:modifica_fase_lavoro', kwargs={'pk':pk_fase})
    
    def form_valid(self, form):        
        messages.info(self.request, self.success_message) # Compare sul success_url
        return super().form_valid(form)
    
    

class FaseLavoroUpdateView(LoginRequiredMixin,UpdateView):
    model = FaseLavoro
    form_class = FaseLavoroModelForm
    template_name = 'articoli/fase_lavoro.html'
    success_message = 'Fase di Lavoro modificata correttamente!'

tannerySuite/articoli/templates/articoli/articoli_home.html
{% extends 'core/base.html' %} 
{% load static %}
{% load crispy_forms_tags %} 
{% load widget_tweaks %}
{% block head_title %}{{ block.super }} - Articoli{% endblock head_title %} 

{% block sidenav %}
{% include "core/partials/_sidenav_articoli.html" %}
{% endblock %}

{% block content %}

<nav aria-label="breadcrumb" class="mt-3">
  <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>      
      <li class="breadcrumb-item active" aria-current="page">Articoli</li>
  </ol>
</nav>
{% include 'core/modals/delConfirm.html' %}



<div class="container">
  <br>
  <h3>Lista Articoli</h3>
  <hr>
  
  <!-- filtro -->
  <div class="row">
    <div class="col">
        <div class="card card-body">
            <form method="get">

                <div class="table-responsive-sm">
                    <table class="table table-hover table-striped table-bordered">
                        <thead class="thead-dark">
                            <tr>     
                                <th>Articolo</th>
                            </tr>
                        </thead>                            
                        <tbody>
                            <tr>                                    
                                <td >{{ filter.form.descrizione|as_crispy_field }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <button class="btn btn-primary" type="submit">Cerca</button>
                <a class="btn btn-success" href="{% url 'articoli:articoli_home' %}"><i class="bi bi-arrow-counterclockwise"></i>&nbsp;&nbsp; Pulisci campi</a>
            </form>        
        </div>
    </div>        
</div>
<!-- fine filtro-->
  <hr>
  {% include "core/partials/_messages.html" %}
  <br>
  

  <a class="btn btn-sm btn-success mt-2 mb-4" href="{% url 'articoli:crea_articolo' %}"><span class="bi bi-person-plus-fill"></span> Aggiungi</a>
  <br>
    <table class="table table-bordered table-striped">
        <thead>
          <tr>
            
            <th>Articolo</th>            
            <th>Scheda Tecnica</th>            
            <th>Azioni</th>

            
          </tr>
        </thead>
        <tbody>
          {% for articolo in filter.qs %}
          <tr>        
            
            
            <td><a href="{% url 'articoli:modifica_articolo' pk=articolo.pk %}">{{ articolo.descrizione }}</a></td>
            {% if articolo.scheda_tecnica %}            
              <td><a href="{{ articolo.scheda_tecnica.url }}" download>{{ articolo.scheda_tecnica }}</a></td>            
            {% else %}
              <td>Non è disponibile una scheda tecnica per questo oggetto.</td>
            {% endif %}
            <td class="text-center"><a href="{% url 'articoli:delete_articolo' pk=articolo.pk %}" class="btn btn-sm btn-outline-danger confirm-delete" title="Delete" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" id="deleteButton{{articolo.pk}}"><i class="bi bi-trash"></i>Elimina</a></td>
          </tr>  
          {% endfor %}
        </tbody>
      </table>
      <!-- Pagination -->
      {% if filter.qs.has_other_pages %}
      <nav>
        <ul class="pagination justify-content-center">
          {% if filter.qs.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ filter.qs.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
          {% else %}
            <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">&laquo;</span>
            </li>
          {% endif %}
  
          {% for p in filter.qs.paginator.page_range %}
            {% if filter.qs.number == p %}
              <li class="page-item"><a class="page-link" style="color: red;" href="#">{{ p }}</a></li>
            {% else %}
              <li class="page-item"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>
            {% endif %}
          {% endfor %}
  
          {% if filter.qs.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ filter.qs.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <span class="page-link" aria-hidden="true">&raquo;</span>
            </li>
          {% endif %}
      </ul>
      </nav>
    {% endif %}
    <!-- End Pagination -->
</div>

{% endblock content %}

tannerySuite/articoli/templates/articoli/caratteristica_procedura.html
{% extends 'core/base.html' %} 
{% load static %}
{% load crispy_forms_tags %} 
{% load widget_tweaks %}
{% block head_title %}{{ block.super }} - Caratteristica Procedura{% endblock head_title %} 

{% block sidenav %}
{% include "core/partials/_sidenav_articoli.html" %}
{% endblock %}

{% block content %}

<div class="container">
    <br>
    <nav aria-label="breadcrumb" class="mt-3">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>      
            <li class="breadcrumb-item"><a href="{% url 'articoli:modifica_dettaglio_procedura' fk_procedura=dettagli_procedura.fk_procedura.pk pk=dettaglio_procedura %}">{{ dettagli_procedura.fk_faselavoro.descrizione }}</a></li>        
    
            {% if form.instance.id  %}
                <li class="breadcrumb-item active" aria-current="page">{{ caratteristicaprocedura.fk_dettaglio_fase_lavoro.attributo }}</li>
            {% else %}
                <li class="breadcrumb-item active" aria-current="page">Aggiungi Caratteristica Procedura</li>
            {% endif %}             
            
            
        </ol>
    </nav>    
    <hr>    
    {% include "core/modals/baseModalGenericSearch.html" %}
    <br>
    {% if form.instance.id  %}
            <h5 class="text-end">{{ fk_dettaglio_fase_lavoro.descrizione }}</h5>
            <h3>Modifica Caratteristica Procedura</h3>
        {% else %}
            <h5 class="text-end">Caratteristica Procedura</h5>
            <h3> Aggiungi Caratteristica Procedura</h3>
        {% endif %}
    
    <!-- Form Articolo -->
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %} 
               <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
               </div>
            {% endfor %}
        {% endfor %}
     {% endif %}
    <div class="form-group mt-3">
        <form class="mt-3" method="POST" novalidate enctype="multipart/form-data">
            {% csrf_token %}
            
            
                    <div class="row mt-3 mb-4">
                      
                      <div class="col-md-12 border rounded shadow-sm">
                        <div class="row">
                            <div class = "col-md-3">
                              {{ form.fk_dettaglio_fase_lavoro|as_crispy_field }}
                            </div>

                            <div class = "col-md-3">
                              {{ form.fk_fornitore|as_crispy_field }}
                            </div>
                            <div class="col-md-1">
                            <button type="button" 
                              class="btn btn-info mt-4" 
                              data-toggle="tooltip" 
                              data-placement="top" 
                              title="Cerca Fornitore" 
                              style="width:100%"
                              id="openSearchSupplierButton"
                              data-bs-toggle="modal" 
                              data-bs-target="#searchModal"
                              data-url="{% url 'core:search_supplier' %}?categoria={{ Fornitore.LAVORAZIONI_ESTERNE }}" 
                              data-modal-title="Cerca Fornitore" 
                              data-search-input-label="Cerca Fornitore"
                              
                              ><i class="bi bi-search"></i></button>
                          </div>
                          </div>
                          <div class="row">
                            <div class = "col-md-3">
                              {{ form.fk_lavorazione_esterna|as_crispy_field }}
                            </div>
                            <div class="col-md-1">
                            <button type="button" 
                              class="btn btn-info mt-4" 
                              data-toggle="tooltip" 
                              data-placement="top" 
                              title="Cerca Lavorazione" 
                              style="width:100%"
                              id="openSearchOutSourcingButton"
                              data-bs-toggle="modal" 
                              data-bs-target="#searchModal"
                              data-url="{% url 'core:search_outsourcing' %}" 
                              data-modal-title="Cerca Lavorazione Esterna" 
                              data-search-input-label="Cerca Lavorazione Esterna per codice o descrizione"
                              
                              ><i class="bi bi-search"></i></button>
                          </div>
                            <div class = "col-md-3">
                              {{ form.valore|as_crispy_field }}
                            </div>
                            </div>
                        </div>
                        <div class="row">
                          <div class = "col-md-3">
                              {{ form.note|as_crispy_field }}
                            </div>
                            <div class = "col-md-3">
                              {{ form.fk_dettaglio_procedura|as_crispy_field }}
                            </div>
                            <div class = "col-md-3">
                              {{ form.numero_riga|as_crispy_field }}
                            </div>
                        </div>
                        
                        <hr>
                        

                        

                    </div>
                      </div>
        <input type="submit" name="salva_esci" class="btn btn-success mb-2 me-1" value="Salva ed Esci">        
        <button type="button" class="btn btn-danger mb-2 me-1" onclick="cancelAndRedirectTo(`{% url 'articoli:modifica_dettaglio_procedura' fk_procedura=dettagli_procedura.fk_procedura.pk pk=dettaglio_procedura %}`)"><i class="bi bi-arrow-counterclockwise"></i> Annulla</button>
                                                                
        <!-- fine form -->
        </form>

        

    </div>
    <hr>
    
    


</div>

{% endblock content %}
{% block extra_scripts %}
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            setFocusOnField('id_descrizione');
        });


    
      document.getElementById('openSearchSupplierButton').addEventListener('click', function(event) {
          var callerButtonId = this.id;
          var url = this.getAttribute('data-url');
          var modalTitle = this.getAttribute('data-modal-title');
          var searchInputLabel = this.getAttribute('data-search-input-label');
          searchFunctionGeneral(url, modalTitle, searchInputLabel, callerButtonId, event);
      });

      document.getElementById('openSearchOutSourcingButton').addEventListener('click', function(event) {
          var callerButtonId = this.id;
          var url = this.getAttribute('data-url');
          var modalTitle = this.getAttribute('data-modal-title');
          var searchInputLabel = this.getAttribute('data-search-input-label');
          console.log("callerButtonId: " + callerButtonId)
          console.log("url: " + url)
          
          searchFunctionGeneral(url, modalTitle, searchInputLabel, callerButtonId, event);
      });




    </script>

{% endblock %}