tannerySuite/acquistopelli/urls.py
from django.urls import path

from .views import (dashboard_acquisto_pelli, tabelle_generiche_acquisto_pelli,
                    LottoCreateView, LottoUpdateView,
                    DettaglioLottoCreateView, DettaglioLottoUpdateView, delete_dettaglio_lotto,
                    SceltaLottoCreateView, SceltaLottoUpdateView, delete_scelta_lotto,
                    TipoAnimaleCreateView, TipoAnimaleUpdateView, delete_tipo_animale,
                    TipoGrezzoCreateView, TipoGrezzoUpdateView, delete_tipo_grezzo,
                    SceltaCreateView, SceltaUpdateView, delete_scelta,
                    SpessoreCreateView, SpessoreUpdateView, delete_spessore,
                    QualityCreateView, QualityUpdateView, delete_quality,
                    TaglioCreateView, TaglioUpdateView, delete_taglio,
                    SezioneCreateView, SezioneUpdateView, delete_sezione,
                    ConciaCreateView, ConciaUpdateView, delete_concia,
                    report_traceability_in
                    )

from .charts import (origine, 
                    origine_per_rpt_lwg, 
                    tipoanimale_per_rpt_lwg,
                    tipogrezzo_per_rpt_lwg
                    )

app_name="acquistopelli"



urlpatterns = [
    # Acquisto pelli dashboard
    path('', dashboard_acquisto_pelli, name="dashboard_acquisto_pelli"),
    path('crea_lotto/', LottoCreateView.as_view(), name="crea_lotto"),
    path('modifica_lotto/<int:pk>/', LottoUpdateView.as_view(), name="modifica_lotto"),
    path('<int:pk>/crea_scelta_lotto/', SceltaLottoCreateView.as_view(), name="crea_scelta_lotto"),
    #path('<int:pk>/modifica_scelta_lotto/<int:id>', SceltaLottoUpdateView.as_view(), name="modifica_scelta_lotto"),
    path('modifica_scelta_lotto/<int:pk>', SceltaLottoUpdateView.as_view(), name="modifica_scelta_lotto"),
    path('delete_scelta_lotto/<int:pk>', delete_scelta_lotto, name="delete_scelta_lotto"),

    # Dettaglio Lotto
    path('<int:pk>/crea_dettaglio_lotto/', DettaglioLottoCreateView.as_view(), name="crea_dettaglio_lotto"),
    path('modifica_dettaglio_lotto/<int:pk>/', DettaglioLottoUpdateView.as_view(), name="modifica_dettaglio_lotto"),
    path('delete_dettaglio_lotto/<int:pk>/', delete_dettaglio_lotto, name="delete_dettaglio_lotto"),
    
    # Tabelle generiche
    path('tabelle_generiche_acquisto_pelli/', tabelle_generiche_acquisto_pelli, name="tabelle_generiche_acquisto_pelli"),

    # Tipo animale    
    path('crea_tipo_animale/', TipoAnimaleCreateView.as_view(), name="crea_tipo_animale"),
    path('modifica_tipo_animale/<int:pk>/', TipoAnimaleUpdateView.as_view(), name="modifica_tipo_animale"),
    path('delete_tipo_animale/<int:pk>/', delete_tipo_animale, name="delete_tipo_animale"),

    # Tipo Grezzo
    path('crea_tipo_grezzo/', TipoGrezzoCreateView.as_view(), name="crea_tipo_grezzo"),
    path('modifica_tipo_grezzo/<int:pk>/', TipoGrezzoUpdateView.as_view(), name="modifica_tipo_grezzo"),
    path('delete_tipo_grezzo/<int:pk>/', delete_tipo_grezzo, name="delete_tipo_grezzo"),
    
    # Spessore    
    path('crea_spessore/', SpessoreCreateView.as_view(), name="crea_spessore"),
    path('modifica_spessore/<int:pk>/', SpessoreUpdateView.as_view(), name="modifica_spessore"),
    path('delete_spessore/<int:pk>/', delete_spessore, name="delete_spessore"),
    
    # Quality
    path('crea_quality/', QualityCreateView.as_view(), name="crea_quality"),
    path('modifica_quality/<int:pk>/', QualityUpdateView.as_view(), name="modifica_quality"),
    path('delete_quality/<int:pk>/', delete_quality, name="delete_quality"),
    
    # Taglio
    path('crea_taglio/', TaglioCreateView.as_view(), name="crea_taglio"),
    path('modifica_taglio/<int:pk>/', TaglioUpdateView.as_view(), name="modifica_taglio"),
    path('delete_taglio/<int:pk>/', delete_taglio, name="delete_taglio"),
    
    # Sezione
    path('crea_sezione/', SezioneCreateView.as_view(), name="crea_sezione"),
    path('modifica_sezione/<int:pk>/', SezioneUpdateView.as_view(), name="modifica_sezione"),
    path('delete_sezione/<int:pk>/', delete_sezione, name="delete_sezione"),
    
    # Concia
    path('crea_concia/', ConciaCreateView.as_view(), name="crea_concia"),
    path('modifica_concia/<int:pk>/', ConciaUpdateView.as_view(), name="modifica_concia"),
    path('delete_concia/<int:pk>/', delete_concia, name="delete_concia"),

    # Scelta
    path('crea_scelta/', SceltaCreateView.as_view(), name="crea_scelta"),
    path('modifica_scelta/<int:pk>/', SceltaUpdateView.as_view(), name="modifica_scelta"),
    path('delete_scelta/<int:pk>/', delete_scelta, name="delete_scelta"),


    # Charts
    path('origine/', origine, name='origine'),
    path('origine_per_rpt_lwg/', origine_per_rpt_lwg, name='origine_per_rpt_lwg'),
    path('tipoanimale_per_rpt_lwg/', tipoanimale_per_rpt_lwg, name='tipoanimale_per_rpt_lwg'),
    #path('tipogrezzo_per_rpt_lwg/', tipogrezzo_per_rpt_lwg, name='tipogrezzo_per_rpt_lwg'),

    # Stampe
    path('report_traceability_in/', report_traceability_in, name='report_traceability_in'),

]

tannerySuite/core/urls.py
from django.urls import path


from .views import *
from .searches import *
from .utils import carica_destinazioni

app_name="core"



urlpatterns = [

    # Facility
    

    # Clienti
    
    
    # Fornitori
    #path("home_fornitori/", home_fornitori, name="home_fornitori"),    
    # Ricerche
    path('search_articolo/', search_articolo, name='search_articolo'),
    path('search_colore/', search_colore, name='search_colore'),
    path('search_supplier/', search_supplier, name='search_supplier'),
    path('search_outsourcing/', search_outsourcing, name='search_outsourcing'),
    path('search_fase_lavoro/', search_fase_lavoro, name="search_fase_lavoro"), # Fase lavoro
    
    path('carica_destinazioni/', carica_destinazioni, name='carica_destinazioni'),

    
]

tannerySuite/acquistopelli/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
import datetime
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView
from django.db.models import Sum


from .filters import LottoFilter

from .models import *

from .forms import *

from .utils import filtro_lotti



def dashboard_acquisto_pelli(request):     
    lotti = Lotto.objects.all()
    
    lotti_filter = LottoFilter(request.GET, queryset=lotti)
    
    page = request.GET.get('page', 1)
    paginator = Paginator(lotti_filter.qs, 50)  # Utilizza lotti_filter.qs per la paginazione
    
        
    try:
        lotti_paginator = paginator.page(page)
    except PageNotAnInteger:
        lotti_paginator = paginator.page(1)
    except EmptyPage:
        lotti_paginator = paginator.page(paginator.num_pages)
        
    context = {
        'lotti_paginator': lotti_paginator,
        'filter': lotti_filter,
    }
    
    return render(request, 'acquistopelli/dashboard_acquisto_pelli.html', context)


class LottoCreateView(LoginRequiredMixin,CreateView):
    model = Lotto
    form_class = LottoModelForm
    template_name = 'acquistopelli/lotto.html'
    success_message = 'Lotto aggiunto correttamente!'
    #success_url = reverse_lazy('human_resources:human_resources')

    def get_success_url(self):        
        if 'salva_esci' in self.request.POST:
            return reverse_lazy('acquistopelli:dashboard_acquisto_pelli')
        
        pk_lotto=self.object.pk
        return reverse_lazy('acquistopelli:modifica_lotto', kwargs={'pk':pk_lotto})
    
    def form_valid(self, form):        
        messages.info(self.request, self.success_message) # Compare sul success_url
        return super().form_valid(form)
    
    def get_initial(self):
        created_by = self.request.user
        return {
            'created_by': created_by,
        }

class LottoUpdateView(LoginRequiredMixin, UpdateView):
    model = Lotto
    form_class = LottoModelForm
    template_name = 'acquistopelli/lotto.html'
    success_message = 'Lotto modificato correttamente!'
    #success_url = reverse_lazy('human_resources:tabelle_generiche_formazione')
    
    def get_success_url(self):        
        if 'salva_esci' in self.request.POST:
            return reverse_lazy('acquistopelli:dashboard_acquisto_pelli')
        
        pk_lotto=self.object.pk
        return reverse_lazy('acquistopelli:modifica_lotto', kwargs={'pk':pk_lotto})
    

    def form_valid(self, form):        
        messages.info(self.request, self.success_message) # Compare sul success_url
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):        
        context = super().get_context_data(**kwargs)
        pk = self.object.pk   
        dettagli_lotto = DettaglioLotto.objects.filter(fk_lotto=pk)
        totale_pezzi = SceltaLotto.objects.filter(fk_lotto=pk).aggregate(Sum('pezzi'))['pezzi__sum'] or 0
        context['scelte_effettuate'] = SceltaLotto.objects.filter(fk_lotto=pk) 
        scelte_effettuate=SceltaLotto.objects.filter(fk_lotto=pk) 
        for scelta in scelte_effettuate:
            print(f"scelta {scelta.fk_scelta.pk}")
            print(f"scelta pezzi {scelta.pezzi}")
            print(f"scelta pk {scelta.pk}")
        context['totale_pezzi'] = totale_pezzi
        lotto = Lotto.objects.get(pk=pk)
        #pezzi_rimanenti = lotto.pezzi - totale_pezzi
        #context['pezzi_rimanenti'] = pezzi_rimanenti
        context['dettagli_lotto'] = dettagli_lotto
        return context

class DettaglioLottoCreateView(LoginRequiredMixin, CreateView):
    model = DettaglioLotto
    form_class = DettaglioLottoModelForm
    template_name = 'acquistopelli/dettaglio_lotto.html'
    success_message = 'Dettaglio aggiunto correttamente!'
    
    def get_initial(self):        
        fk_lotto = self.kwargs['pk'] 
        print("Lotto initial:" + str(fk_lotto))
        created_by = self.request.user       
        return {
            'fk_lotto': fk_lotto,
            'created_by': created_by
        }

    def get_success_url(self):          
        fk_lotto=self.object.fk_lotto.pk   
        print("fkLotto: " + str(fk_lotto))     
        return reverse_lazy('acquistopelli:modifica_lotto', kwargs={'pk':fk_lotto})
    
    def form_valid(self, form):                
        messages.info(self.request, self.success_message) # Compare sul success_url
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):        
        context = super().get_context_data(**kwargs)
        pk = self.kwargs['pk']       
        context['fk_lotto'] = Lotto.objects.get(pk=pk) 
        return context
    
    
class DettaglioLottoUpdateView(LoginRequiredMixin, UpdateView):
    model = DettaglioLotto
    form_class = DettaglioLottoModelForm
    template_name = 'acquistopelli/dettaglio_lotto.html'
    success_message = 'Dettaglio modificato correttamente!'
    #success_url = reverse_lazy('human_resources:crea_registro_formazione', kwargs={"pk": pk})
    
    def get_success_url(self):          
        fk_lotto=self.object.fk_lotto.pk        
        return reverse_lazy('acquistopelli:modifica_lotto', kwargs={'pk':fk_lotto})
    
    def form_valid(self, form):                
        messages.info(self.request, self.success_message) # Compare sul success_url
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):        
        context = super().get_context_data(**kwargs)
        pk = self.kwargs['pk']       
        context['fk_lotto'] = Lotto.objects.get(pk=pk)
        return context
    


def delete_dettaglio_lotto(request, pk): 
        deleteobject = get_object_or_404(DettaglioLotto, pk = pk)   
        fk_lotto = deleteobject.fk_lotto.pk      
        deleteobject.delete()
        url_match = reverse_lazy('acquistopelli:modifica_lotto', kwargs={'pk':fk_lotto})
        return redirect(url_match)

# Dettaglio scelta lotto
class SceltaLottoCreateView(LoginRequiredMixin, CreateView):
    model = SceltaLotto
    form_class = SceltaLottoModelForm
    template_name = 'acquistopelli/scelta_lotto.html'
    success_message = 'Dettaglio aggiunto correttamente!'
    
    def get_initial(self):        
        fk_lotto = self.kwargs['pk'] 
        print("Lotto initial:" + str(fk_lotto))
        created_by = self.request.user       
        return {
            'fk_lotto': fk_lotto,
            'created_by': created_by
        }

    def get_success_url(self):          
        fk_lotto=self.object.fk_lotto.pk   
        print("fkLotto: " + str(fk_lotto))     
        return reverse_lazy('acquistopelli:modifica_lotto', kwargs={'pk':fk_lotto})
    
    def form_valid(self, form):                
        messages.info(self.request, self.success_message) # Compare sul success_url
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):        
        context = super().get_context_data(**kwargs)
        pk = self.kwargs['pk']       
        context['fk_lotto'] = Lotto.objects.get(pk=pk) 
        return context
    
    
class SceltaLottoUpdateView(LoginRequiredMixin, UpdateView):
    model = SceltaLotto
    form_class = SceltaLottoModelForm
    template_name = 'acquistopelli/scelta_lotto.html'
    success_message = 'Dettaglio modificato correttamente!'
    #success_url = reverse_lazy('human_resources:crea_registro_formazione', kwargs={"pk": pk})
    
    def get_success_url(self):          
        fk_lotto=self.object.fk_lotto.pk        
        return reverse_lazy('acquistopelli:modifica_lotto', kwargs={'pk':fk_lotto})
    
    def form_valid(self, form):                
        messages.info(self.request, self.success_message) # Compare sul success_url
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):        
        context = super().get_context_data(**kwargs)
        pk = self.kwargs['pk']       
        context['fk_lotto'] = Lotto.objects.get(pk=pk)
        return context
    


def delete_scelta_lotto(request, pk): 
        deleteobject = get_object_or_404(SceltaLotto, pk = pk)   
        fk_lotto = deleteobject.fk_lotto.pk      
        deleteobject.delete()
        url_match = reverse_lazy('acquistopelli:modifica_lotto', kwargs={'pk':fk_lotto})
        return redirect(url_match)


'''SEZIONE TABELLE GENERICHE'''

def tabelle_generiche_acquisto_pelli(request):
    tipianimale = TipoAnimale.objects.all()
    tipigrezzo = TipoGrezzo.objects.all()
    scelte = Scelta.objects.all()
    spessori = Spessore.objects.all()
    qualities = Quality.objects.all()
    tagli = Taglio.objects.all()
    sezioni = Sezione.objects.all()
    conce = Concia.objects.all()
    

    context = {'tipianimale': tipianimale, 
                'tipigrezzo': tipigrezzo,  
                'scelte': scelte,
                'spessori': spessori,
                'qualities': qualities,
                'tagli': tagli,
                'sezioni': sezioni,
                'conce': conce
                }
    
    return render(request, "acquistopelli/tabelle_generiche_acquisto_pelli.html", context)


class TipoAnimaleCreateView(LoginRequiredMixin,CreateView):
    model = TipoAnimale
    form_class = TipoAnimaleModelForm
    template_name = 'acquistopelli/generiche/tipo_animale.html'
    success_message = 'Tipo Animale aggiunto correttamente!'
    success_url = reverse_lazy('acquistopelli:tabelle_generiche_acquisto_pelli')
  
    def form_valid(self, form):        
        messages.info(self.request, self.success_message) # Compare sul success_url
        return super().form_valid(form)
    
    def get_initial(self):
        created_by = self.request.user
        return {
            'created_by': created_by,
        }
    

tannerySuite/acquistopelli/templates/acquistopelli/partials/_concia_table.html
<div class="col-4">
    <div class="row">
      <div class="col-6">
        <h5>Concia</h5>                  
      </div>
      <div class="col-6 text-end">
        <a href="{% url 'acquistopelli:crea_concia' %}" class="btn btn-sm btn-success"><i class="bi bi-file-earmark-plus"></i> Aggiungi Concia</a>
      </div>
    </div>
    <div class="table-container">
      <table class="table table-bordered table-striped mt-2">
        <thead>
          <tr>
            <th>Descrizione</th>            
            <th>Azione</th>
            
          </tr>
        </thead>
        <tbody>
          {% for concia in conce %}
          <tr>        
            
            <td><a href="{% url 'acquistopelli:modifica_concia' pk=concia.pk %}">{{ concia.descrizione }}</a></td>
            
            <td class="text-center"><a href="{% url 'acquistopelli:delete_concia' pk=concia.pk %}" class="btn btn-sm btn-outline-danger confirm-delete" title="Delete" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" id="deleteButton{{concia.pk}}"><i class="bi bi-trash"></i>Elimina</a></td>
          </tr>  
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

tannerySuite/acquistopelli/templates/acquistopelli/partials/_quality_table.html
<div class="col-4">
    <div class="row">
      <div class="col-6">
        <h5>Qualità</h5>                  
      </div>
      <div class="col-6 text-end">
        <a href="{% url 'acquistopelli:crea_quality' %}" class="btn btn-sm btn-success"><i class="bi bi-file-earmark-plus"></i> Aggiungi Qualità</a>
      </div>
    </div>
    <div class="table-container">
      <table class="table table-bordered table-striped mt-2">
        <thead>
          <tr>
            <th>Descrizione</th>            
            <th>Azione</th>
            
          </tr>
        </thead>
        <tbody>
          {% for quality in qualities %}
          <tr>        
            
            <td><a href="{% url 'acquistopelli:modifica_quality' pk=quality.pk %}">{{ quality.descrizione }}</a></td>
            
            <td class="text-center"><a href="{% url 'acquistopelli:delete_quality' pk=quality.pk %}" class="btn btn-sm btn-outline-danger confirm-delete" title="Delete" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" id="deleteButton{{quality.pk}}"><i class="bi bi-trash"></i>Elimina</a></td>
          </tr>  
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

tannerySuite/acquistopelli/templates/acquistopelli/partials/_scelta_table.html
<div class="col-6">
  <div class="row">
    <div class="col-6">
      <h5>Scelte</h5>                  
    </div>
    <div class="col-6 text-end">
      <a href="{% url 'acquistopelli:crea_scelta' %}" class="btn btn-sm btn-success"><i class="bi bi-file-earmark-plus"></i> Aggiungi Scelta</a>
    </div>
  </div>
  <div class="table-container">
    <table class="table table-bordered table-striped mt-2">
      <thead>
        <tr>
          <th>Descrizione</th>            
          <th>Azione</th>
          
        </tr>
      </thead>
      <tbody>
        {% for scelta in scelte %}
        <tr>        
          
          <td><a href="{% url 'acquistopelli:modifica_scelta' pk=scelta.pk %}">{{ scelta.descrizione }}</a></td>
          
          <td class="text-center"><a href="{% url 'acquistopelli:delete_scelta' pk=scelta.pk %}" class="btn btn-sm btn-outline-danger confirm-delete" title="Delete" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" id="deleteButton{{scelta.pk}}"><i class="bi bi-trash"></i>Elimina</a></td>
        </tr>  
        {% endfor %}
      </tbody>
    </table>
    </div>
</div>

</div>

tannerySuite/acquistopelli/templates/acquistopelli/partials/_sezione_table.html
<div class="col-4">
    <div class="row">
      <div class="col-6">
        <h5>Sezione</h5>                  
      </div>
      <div class="col-6 text-end">
        <a href="{% url 'acquistopelli:crea_sezione' %}" class="btn btn-sm btn-success"><i class="bi bi-file-earmark-plus"></i> Aggiungi Sezione</a>
      </div>
    </div>
    <div class="table-container">
      <table class="table table-bordered table-striped mt-2">
        <thead>
          <tr>
            <th>Descrizione</th>            
            <th>Azione</th>
            
          </tr>
        </thead>
        <tbody>
          {% for sezione in sezioni %}
          <tr>        
            
            <td><a href="{% url 'acquistopelli:modifica_sezione' pk=sezione.pk %}">{{ sezione.descrizione }}</a></td>
            
            <td class="text-center"><a href="{% url 'acquistopelli:delete_sezione' pk=sezione.pk %}" class="btn btn-sm btn-outline-danger confirm-delete" title="Delete" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" id="deleteButton{{sezione.pk}}"><i class="bi bi-trash"></i>Elimina</a></td>
          </tr>  
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

tannerySuite/acquistopelli/templates/acquistopelli/partials/_spessore_table.html
<div class="col-4">
    <div class="row">
      <div class="col-6">
        <h5>Spessore</h5>                  
      </div>
      <div class="col-6 text-end">
        <a href="{% url 'acquistopelli:crea_spessore' %}" class="btn btn-sm btn-success"><i class="bi bi-file-earmark-plus"></i> Aggiungi Spessore</a>
      </div>
    </div>
    <div class="table-container">
      <table class="table table-bordered table-striped mt-2">
        <thead>
          <tr>
            <th>Descrizione</th>            
            <th>Azione</th>
            
          </tr>
        </thead>
        <tbody>
          {% for spessore in spessori %}
          <tr>        
            
            <td><a href="{% url 'acquistopelli:modifica_spessore' pk=spessore.pk %}">{{ spessore.descrizione }}</a></td>
            
            <td class="text-center"><a href="{% url 'acquistopelli:delete_spessore' pk=spessore.pk %}" class="btn btn-sm btn-outline-danger confirm-delete" title="Delete" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" id="deleteButton{{spessore.pk}}"><i class="bi bi-trash"></i>Elimina</a></td>
          </tr>  
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

tannerySuite/acquistopelli/templates/acquistopelli/partials/_taglio_table.html
<div class="col-4">
    <div class="row">
      <div class="col-6">
        <h5>Taglio</h5>                  
      </div>
      <div class="col-6 text-end">
        <a href="{% url 'acquistopelli:crea_taglio' %}" class="btn btn-sm btn-success"><i class="bi bi-file-earmark-plus"></i> Aggiungi Taglio</a>
      </div>
    </div>
    <div class="table-container">
      <table class="table table-bordered table-striped mt-2">
        <thead>
          <tr>
            <th>Descrizione</th>            
            <th>Azione</th>
            
          </tr>
        </thead>
        <tbody>
          {% for taglio in tagli %}
          <tr>        
            
            <td><a href="{% url 'acquistopelli:modifica_taglio' pk=taglio.pk %}">{{ taglio.descrizione }}</a></td>
            
            <td class="text-center"><a href="{% url 'acquistopelli:delete_taglio' pk=taglio.pk %}" class="btn btn-sm btn-outline-danger confirm-delete" title="Delete" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" id="deleteButton{{taglio.pk}}"><i class="bi bi-trash"></i>Elimina</a></td>
          </tr>  
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

tannerySuite/acquistopelli/templates/acquistopelli/partials/_tipo_animale_table.html
<div class="col-4">
    <div class="row">
      <div class="col-6">
        <h5>Tipo Animale</h5>                  
      </div>
      <div class="col-6 text-end">
        <a href="{% url 'acquistopelli:crea_tipo_animale' %}" class="btn btn-sm btn-success"><i class="bi bi-file-earmark-plus"></i> Aggiungi Tipo Animale</a>
      </div>
    </div>
    <div class="table-container">
      <table class="table table-bordered table-striped mt-2">
        <thead>
          <tr>
            <th>Descrizione</th>            
            <th>Azione</th>
            
          </tr>
        </thead>
        <tbody>
          {% for tipoanimale in tipianimale %}
          <tr>        
            
            <td><a href="{% url 'acquistopelli:modifica_tipo_animale' pk=tipoanimale.pk %}">{{ tipoanimale.descrizione }}</a></td>
            
            <td class="text-center"><a href="{% url 'acquistopelli:delete_tipo_animale' pk=tipoanimale.pk %}" class="btn btn-sm btn-outline-danger confirm-delete" title="Delete" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" id="deleteButton{{tipoanimale.pk}}"><i class="bi bi-trash"></i>Elimina</a></td>
          </tr>  
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

tannerySuite/acquistopelli/templates/acquistopelli/partials/_tipo_grezzo_table.html
<div class="col-6">
    <div class="row">
      <div class="col-6">
        <h5>Tipo Grezzo</h5>                  
      </div>
      <div class="col-6 text-end">
        <a href="{% url 'acquistopelli:crea_tipo_grezzo' %}" class="btn btn-sm btn-success"><i class="bi bi-file-earmark-plus"></i> Aggiungi Tipo Grezzo</a>
      </div>
    </div>
    <div class="table-container">
      <table class="table table-bordered table-striped mt-2">
        <thead>
          <tr>
            <th>Descrizione</th>            
            <th>Azione</th>
            
          </tr>
        </thead>
        <tbody>
          {% for tipogrezzo in tipigrezzo %}
          <tr>        
            
            <td><a href="{% url 'acquistopelli:modifica_tipo_grezzo' pk=tipogrezzo.pk %}">{{ tipogrezzo.descrizione }}</a></td>
            
            <td class="text-center"><a href="{% url 'acquistopelli:delete_tipo_grezzo' pk=tipogrezzo.pk %}" class="btn btn-sm btn-outline-danger confirm-delete" title="Delete" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" id="deleteButton{{tipogrezzo.pk}}"><i class="bi bi-trash"></i>Elimina</a></td>
          </tr>  
          {% endfor %}
        </tbody>
      </table>
      </div>
  </div>